### ISSUE TITLE
Colon-less syntax doesn't get highlighting

### ISSUE THREAD

**Issue by jasonkuhrt** [wavded/vim-stylus#11]
Currently this:

```
body
    width 100px
```

and

```
body
    width: 100px
```

produce different results. `width:` receives syntax highlighting but `width` doesn't. I believe the line to fix this is at https://github.com/wavded/vim-stylus/blob/master/syntax/stylus.vim#L61 but I haven't been able to get it working so far. I don't understand the vim syntax syntax well enough.

**Comment by onenglar** [comment]
same problem 2020
