### ISSUE TITLE
Syntax highlighting doesn't work when using Vundle for package management

### ISSUE THREAD

**Issue by wamoyo** [wavded/vim-stylus#26]
I'm using Vundle for Vim package management and vim-stylus isn't working. I have this line in my .vimrc file `autocmd BufNewFile,BufRead *.styl set filetype=styl` and when I check the filetype in my stylus files it shows `filetype=styl` so that's working. All the text is still grey though. Would love some help : )

**Comment by chaseadamsio** [comment]
Even though this is an older issue, I'm using `vundle` as well and hit this same roadblock. I didn't have a `styl set filetype`, but I added @wamoyo's suggestion and it fixed mine as well:

```
autocmd BufNewFile,BufRead *.styl set filetype=stylus
```
