### ISSUE TITLE
Started port to upstream VIM

### ISSUE THREAD

**Issue by pheiduck** [wavded/vim-stylus#52]
Hey @wavded,

I started to Port this Plugin to upstream VIM
https://github.com/vim/vim/pull/14656
Please take a Review if you can and help to improve. I pinged all Maintainers which are included here.

Best regards,
Philip Heiduck

**Comment by wavded** [comment]
Sounds great, it's been years since I've seriously looked at this plugin. Think the community would benefit from an official upstream VIM version.
